from __future__ import annotations

from pathlib import Path
import math
import re
import tempfile
from typing import Any

import numpy as np
import pandapower as pp

from pandapower.converter.matpower.from_mpc import from_mpc
from pandapower.converter.matpower.to_mpc import to_mpc

from powermodelconverter.adapters.base import ExportAdapter, ImportAdapter
from powermodelconverter.adapters.pandapower_adapter import PandapowerAdapter
from powermodelconverter.core.model import CanonicalCase


class MatpowerImportAdapter(ImportAdapter):
    source_format = "matpower"

    def __init__(self) -> None:
        self._pandapower = PandapowerAdapter()

    def import_case(self, source: str | Path, **kwargs: Any) -> CanonicalCase:
        path = Path(source)
        source_text = path.read_text()
        try:
            net = from_mpc(str(path), **kwargs)
        except ValueError as exc:
            if "max() iterable argument is empty" not in str(exc):
                raise
            normalized = _normalize_matpower_matrix_rows(source_text)
            with tempfile.NamedTemporaryFile("w", suffix=".m", delete=False) as handle:
                handle.write(normalized)
                normalized_path = Path(handle.name)
            try:
                net = from_mpc(str(normalized_path), **kwargs)
            finally:
                normalized_path.unlink(missing_ok=True)
        _ensure_reference_bus_from_matpower_source(net, source_text)
        return self._pandapower.to_canonical(
            net,
            case_id=path.stem,
            source_format=self.source_format,
            metadata={"import_backend": "pandapower.from_mpc"},
            source_path=path,
        )


class MatpowerExportAdapter(ExportAdapter):
    target_format = "matpower"

    def __init__(self) -> None:
        self._pandapower = PandapowerAdapter()

    def export_case(self, case: CanonicalCase, destination: str | Path, **kwargs: Any) -> Path:
        path = Path(destination)
        path.parent.mkdir(parents=True, exist_ok=True)
        net = self._pandapower.run_power_flow(case)
        export_kwargs = {"init": "results", **kwargs}
        mpc = to_mpc(net, **export_kwargs)["mpc"]
        path.write_text(_serialize_matpower_case(path.stem, mpc))
        return path


def _normalize_matpower_matrix_rows(contents: str) -> str:
    normalized_lines: list[str] = []
    inside_matrix = False

    for line in contents.splitlines():
        stripped = line.strip()
        if stripped.startswith("%"):
            continue
        if not inside_matrix and "= [" in line:
            inside_matrix = True
            normalized_lines.append(line)
            continue

        if inside_matrix:
            if stripped == "];":
                inside_matrix = False
                normalized_lines.append(line)
                continue
            if not stripped:
                normalized_lines.append(line)
                continue
            if not stripped.endswith(";"):
                line = f"{line.rstrip()};"

        normalized_lines.append(line)

    return "\n".join(normalized_lines) + "\n"


def _ensure_reference_bus_from_matpower_source(net: Any, contents: str) -> None:
    if not net.ext_grid.empty:
        return
    if "slack" in net.gen.columns and bool(net.gen["slack"].fillna(False).any()):
        return

    for row in _parse_matpower_matrix(contents, "bus"):
        if len(row) < 8:
            continue
        bus_id = int(float(row[0]))
        bus_type = int(float(row[1]))
        vm_pu = float(row[7])
        if bus_type != 3:
            continue

        candidate_indices = [bus_id - 1]
        if bus_id in net.bus.index:
            candidate_indices.insert(0, bus_id)

        chosen_index = next((idx for idx in candidate_indices if idx in net.bus.index), None)
        if chosen_index is None:
            continue

        pp.create_ext_grid(net, bus=chosen_index, vm_pu=vm_pu)
        return


def _parse_matpower_matrix(contents: str, matrix_name: str) -> list[list[str]]:
    normalized = _normalize_matpower_matrix_rows(contents)
    match = re.search(rf"mpc\.{re.escape(matrix_name)}\s*=\s*\[(.*?)\];", normalized, re.DOTALL)
    if not match:
        return []

    rows: list[list[str]] = []
    for raw_line in match.group(1).splitlines():
        stripped = raw_line.strip().rstrip(";")
        if not stripped:
            continue
        rows.append(stripped.split())
    return rows


def _serialize_matpower_case(case_name: str, mpc: dict[str, Any]) -> str:
    lines = [
        f"function mpc = {case_name}",
        f"%% MATPOWER case generated by {__name__}",
        "",
        "%% MATPOWER Case Format : Version 2",
        f"mpc.version = '{mpc.get('version', '2')}';",
        "",
        "%% system MVA base",
        f"mpc.baseMVA = {_format_matpower_scalar(mpc.get('baseMVA', 100.0))};",
        "",
    ]
    for matrix_name in ("bus", "gen", "branch", "gencost"):
        matrix = mpc.get(matrix_name)
        if matrix is None:
            continue
        lines.extend(_serialize_matpower_matrix(matrix_name, matrix))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _serialize_matpower_matrix(name: str, matrix: Any) -> list[str]:
    array = np.asarray(matrix)
    expected_columns = {
        "bus": 13,
        "gen": 21,
        "branch": 13,
    }.get(name)
    if expected_columns is not None and array.ndim >= 2:
        array = array[:, :expected_columns]
    lines = [f"mpc.{name} = ["]
    if array.size:
        for row in np.atleast_2d(array):
            formatted = "\t".join(_format_matpower_scalar(value) for value in row)
            lines.append(f"\t{formatted};")
    lines.append("];")
    return lines


def _format_matpower_scalar(value: Any) -> str:
    if isinstance(value, str):
        return value
    number = float(value)
    if math.isnan(number):
        return "NaN"
    if math.isinf(number):
        return "Inf" if number > 0 else "-Inf"
    if number.is_integer():
        return str(int(number))
    return f"{number:.12g}"
