from __future__ import annotations

ROUTE_CATALOG_BY_TARGET = {
    'cgmes': [
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'cgmes_smoke',
            'notes': 'Transformer-free balanced pandapower subset exported to CGMES and validated by native pandapower CGMES re-import.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
    ],
    'matpower': [
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
    ],
    'opendss': [
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_branch_loads',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_phase_skew',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_radial_loads',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced_subset',
            'case_id': 'minimal_radial.pandapower',
            'notes': 'Balanced pandapower re-import of the OpenDSS starter feeder exported back to OpenDSS and validated against pandapower AC power flow.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_branch_loads.pandapower',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_phase_skew.pandapower',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_radial_loads.pandapower',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'ieee_european_lv_asymmetric',
            'notes': 'Native pandapower 3-phase model exported to OpenDSS and validated against runpp_3ph node voltages.',
            'requires': [],
        },
        {
            'source_tool': 'powermodelsdistribution',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_branch_loads_pmd',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'powermodelsdistribution',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_phase_skew_pmd',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'powermodelsdistribution',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_radial_loads_pmd',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
    ],
    'pandapower': [
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'cgmes',
            'notes': "Official pandapower SmallGrid CGMES sample imported through pandapower's native CGMES loader.",
            'requires': [],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'case9',
            'notes': 'Official MATPOWER case9 imported through pandapower converter.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced_subset',
            'case_id': 'minimal_chain',
            'notes': 'OpenDSS native chained feeder with two loads validated against source bus voltages through pandapower.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced_subset',
            'case_id': 'minimal_radial',
            'notes': 'Validated against OpenDSS source slack power and bus voltages for the currently supported subset.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_branch_loads',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_phase_skew',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_radial_loads',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'minimal_unbalanced_3ph',
            'notes': 'Unbalanced OpenDSS starter feeder validated against source node voltages with pandapower runpp_3ph.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'minimal_unbalanced_branch',
            'notes': 'OpenDSS native branched unbalanced feeder validated against source node voltages through pandapower.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'case9_from_matpower.pandapower',
            'notes': 'Pandapower JSON re-import generated from the validated MATPOWER case9 route.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_branch_loads.pandapower',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_phase_skew.pandapower',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_radial_loads.pandapower',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'ieee_european_lv_asymmetric',
            'notes': 'Native pandapower 3-phase roundtrip validated with runpp_3ph.',
            'requires': [],
        },
        {
            'source_tool': 'pm.jl',
            'model_type': 'balanced',
            'case_id': 'case30_pmjl_pkg',
            'notes': 'pm.jl package-native MATPOWER case30 imported into pandapower and validated against deterministic pandapower AC power flow.',
            'requires': [],
        },
        {
            'source_tool': 'powermodelsdistribution',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_branch_loads_pmd',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'powermodelsdistribution',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_phase_skew_pmd',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'powermodelsdistribution',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_radial_loads_pmd',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': [],
        },
        {
            'source_tool': 'pypower',
            'model_type': 'balanced',
            'case_id': 'DTU7K_26',
            'notes': "Skipped strict bilateral validation for DTU7K subnet 26 because one side did not converge: newtonpf() missing 1 required positional argument: 'options'.",
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'case9_from_matpower.pandapower.pypsa',
            'notes': 'PyPSA NetCDF re-import validated against PyPSA AC power flow and converted back through pandapower for the current line-based balanced subset.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'pypsa_five_bus_ring_native',
            'notes': 'Native PyPSA five-bus ring with distributed load validated against PyPSA AC power flow through pandapower.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'pypsa_radial_native',
            'notes': 'Native PyPSA radial transmission-style case validated against PyPSA AC power flow through pandapower.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'pypsa_triangle_native',
            'notes': 'Native PyPSA meshed triangle with one slack, one PV generator, and two loads validated against PyPSA AC power flow through pandapower.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa-eur',
            'model_type': 'balanced',
            'case_id': 'pypsa_eur_base_synthetic_pf',
            'notes': 'PyPSA-Eur artifact tracked from `pypsa_eur_base_synthetic_pf.validation.json` with scope `ac_projection_against_pypsa`. See the JSON artifact for the full export metadata. Validation skipped: PyPSA reference power flow failed: None.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa-eur',
            'model_type': 'balanced',
            'case_id': 'pypsa_eur_full_base_island_validated',
            'notes': 'PyPSA-Eur artifact tracked from `pypsa_eur_full_base_island_validated.validation.json` with scope `ac_projection_against_pypsa`. See the JSON artifact for the full export metadata.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa-eur',
            'model_type': 'balanced',
            'case_id': 'pypsa_eur_full_base_network',
            'notes': 'PyPSA-Eur artifact tracked from `pypsa_eur_full_base_network.validation.json` with scope `ac_projection_against_pypsa`. See the JSON artifact for the full export metadata. Validation skipped: Requested by --skip-validation.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa-eur',
            'model_type': 'balanced',
            'case_id': 'pypsa_eur_full_base_pf_validated',
            'notes': 'PyPSA-Eur artifact tracked from `pypsa_eur_full_base_pf_validated.validation.json` with scope `ac_projection_against_pypsa`. See the JSON artifact for the full export metadata. Validation skipped: PyPSA reference power flow failed: None.',
            'requires': [],
        },
    ],
    'powermodels': [
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'cgmes',
            'notes': 'Official CGMES sample exported onward to PowerModels and validated with Julia AC power flow.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'case9',
            'notes': 'Balanced export validated with Julia PowerModels AC power flow.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced_subset',
            'case_id': 'minimal_radial',
            'notes': 'Balanced-equivalent export validated with Julia PowerModels AC power flow.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'case33bw',
            'notes': 'Pandapower package Baran-Wu 33-bus feeder validated with Julia PowerModels AC power flow.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'case6ww',
            'notes': 'Pandapower package case6ww validated with Julia PowerModels AC power flow.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'case9_from_matpower.pandapower',
            'notes': 'Balanced pandapower JSON export validated with Julia PowerModels AC power flow.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'pm.jl',
            'model_type': 'balanced',
            'case_id': 'case30_pmjl_pkg',
            'notes': 'pm.jl package-native MATPOWER case30 imported to canonical, exported back to PowerModels JSON, and validated with Julia PowerModels AC power flow.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': ['julia-pm'],
        },
    ],
    'powermodelsdistribution': [
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_branch_loads',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': ['julia-pmd'],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_phase_skew',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': ['julia-pmd'],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_radial_loads',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': ['julia-pmd'],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'minimal_unbalanced_3ph',
            'notes': 'Unbalanced OpenDSS starter feeder exported to PowerModelsDistribution and validated against source node voltages.',
            'requires': ['julia-pmd'],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'unbalanced_3ph',
            'case_id': 'minimal_unbalanced_branch',
            'notes': 'OpenDSS native branched unbalanced feeder validated against source node voltages through PowerModelsDistribution.',
            'requires': ['julia-pmd'],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_branch_loads.pandapower',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': ['julia-pmd'],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_phase_skew.pandapower',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': ['julia-pmd'],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_radial_loads.pandapower',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': ['julia-pmd'],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'unbalanced_3ph',
            'case_id': 'ieee_european_lv_asymmetric',
            'notes': 'Native pandapower 3-phase model exported to PowerModelsDistribution and validated against runpp_3ph node voltages.',
            'requires': ['julia-pmd'],
        },
        {
            'source_tool': 'powermodelsdistribution',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_branch_loads_pmd',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': ['julia-pmd'],
        },
        {
            'source_tool': 'powermodelsdistribution',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_phase_skew_pmd',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': ['julia-pmd'],
        },
        {
            'source_tool': 'powermodelsdistribution',
            'model_type': 'unbalanced_3ph',
            'case_id': 'core_unb_radial_loads_pmd',
            'notes': 'Unbalanced common-subset interoperability case. Supported elements: one slack source, buses, lines, native asymmetric loads, and the current signed-off transformer subset.',
            'requires': ['julia-pmd'],
        },
    ],
    'powersystems': [
        {
            'source_tool': 'powersystems.jl',
            'model_type': 'balanced',
            'case_id': 'case30_powersystems_pkg',
            'notes': 'MATPOWER case30 imported to canonical, exported through the PowerSystems.jl route, and validated with PowerSimulations.jl AC power flow.',
            'requires': ['julia-psi'],
        },
    ],
    'pypsa': [
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'cgmes',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.cgmes',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'matpower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'opendss',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'case4gs',
            'notes': 'Pandapower package case4gs validated through PyPSA on the supported balanced AC subset.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'case5',
            'notes': 'Pandapower package case5 validated through PyPSA on the supported balanced AC subset.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'case9_from_matpower.pandapower',
            'notes': 'Balanced line-based pandapower model exported to PyPSA NetCDF and validated against pandapower AC power flow.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pandapower',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus.pandapower',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_radial_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_ring_4bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
        {
            'source_tool': 'pypsa',
            'model_type': 'balanced',
            'case_id': 'core_bal_star_3bus',
            'notes': 'Balanced common-subset interoperability case. Supported elements: one slack source, buses, lines, and constant-power loads.',
            'requires': [],
        },
    ],
}

