from __future__ import annotations

from pathlib import Path
import math
from typing import Any

import numpy as np
from pandapower.converter.matpower.to_mpc import to_mpc

from powermodelconverter.core.contracts import ExportAdapter
from powermodelconverter.core.pandapower_backend import PandapowerAdapter
from powermodelconverter.core.model import CanonicalCase
from powermodelconverter.core.registry import register_target_routes
from powermodelconverter.validation.tolerances import BALANCED_TOLERANCES


class MatpowerExportAdapter(ExportAdapter):
    target_format = "matpower"

    def export_case(self, case: CanonicalCase, destination: str | Path, **kwargs: Any) -> Path:
        return export_matpower(case, destination, **kwargs)


def export_matpower(case: CanonicalCase, output_path: str | Path, **kwargs: Any) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    net = PandapowerAdapter().run_power_flow(case)
    export_kwargs = {"init": "results", **kwargs}
    mpc = to_mpc(net, **export_kwargs)["mpc"]
    path.write_text(_serialize_matpower_case(path.stem, mpc))
    return path


def _serialize_matpower_case(case_name: str, mpc: dict[str, Any]) -> str:
    lines = [
        f"function mpc = {case_name}",
        f"%% MATPOWER case generated by {__name__}",
        "",
        "%% MATPOWER Case Format : Version 2",
        f"mpc.version = '{mpc.get('version', '2')}';",
        "",
        "%% system MVA base",
        f"mpc.baseMVA = {_format_matpower_scalar(mpc.get('baseMVA', 100.0))};",
        "",
    ]
    for matrix_name in ("bus", "gen", "branch", "gencost"):
        matrix = mpc.get(matrix_name)
        if matrix is None:
            continue
        lines.extend(_serialize_matpower_matrix(matrix_name, matrix))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _serialize_matpower_matrix(name: str, matrix: Any) -> list[str]:
    array = np.asarray(matrix)
    expected_columns = {
        "bus": 13,
        "gen": 21,
        "branch": 13,
    }.get(name)
    if expected_columns is not None and array.ndim >= 2:
        array = array[:, :expected_columns]
    lines = [f"mpc.{name} = ["]
    if array.size:
        for row in np.atleast_2d(array):
            formatted = "\t".join(_format_matpower_scalar(value) for value in row)
            lines.append(f"\t{formatted};")
    lines.append("];")
    return lines


def _format_matpower_scalar(value: Any) -> str:
    if isinstance(value, str):
        return value
    number = float(value)
    if math.isnan(number):
        return "NaN"
    if math.isinf(number):
        return "Inf" if number > 0 else "-Inf"
    if number.is_integer():
        return str(int(number))
    return f"{number:.12g}"


register_target_routes(target_tool="matpower", exporter=export_matpower, tolerances=BALANCED_TOLERANCES)


__all__ = ["MatpowerExportAdapter", "export_matpower"]
